name: Continuous integration
on: [push, pull_request]

jobs:
  linux:
    name: Build (Linux, GCC)
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Set up Python (for SCons)
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config
          python -m pip install scons

      - name: Build godot-cpp
        run: |
          scons target=release generate_bindings=yes -j $(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: godot-cpp-linux-glibc2.23-x86_64-release
          path: bin/libgodot-cpp.linux.release.64.a
          if-no-files-found: error

  windows-msvc:
    name: Build (Windows, MSVC)
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Set up Python (for SCons)
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      - name: Install dependencies
        run: |
          python -m pip install scons

      - name: Build godot-cpp
        run: |
          scons target=release generate_bindings=yes -j $env:NUMBER_OF_PROCESSORS

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: godot-cpp-windows-msvc2019-x86_64-release
          path: bin/libgodot-cpp.windows.release.64.lib
          if-no-files-found: error

  windows-mingw:
    name: Build (Windows, MinGW)
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Set up Python (for SCons)
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      - name: Install dependencies
        run: |
          python -m pip install scons

      - name: Build godot-cpp
        # Install GCC from Scoop as the default supplied GCC doesn't work ("Error 1").
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop install gcc
          g++ --version
          gcc --version
          scons target=release generate_bindings=yes use_mingw=yes -j $env:NUMBER_OF_PROCESSORS

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: godot-cpp-linux-mingw-x86_64-release
          path: bin/libgodot-cpp.windows.release.64.a
          if-no-files-found: error

  macos:
    name: Build (macOS, Clang)
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Set up Python (for SCons)
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      - name: Install dependencies
        run: |
          python -m pip install scons

      - name: Build godot-cpp
        run: |
          scons target=release generate_bindings=yes -j $(sysctl -n hw.logicalcpu)

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: godot-cpp-macos-x86_64-release
          path: bin/libgodot-cpp.osx.release.64.a
          if-no-files-found: error
